Repository torrust/torrust-tracker, pull requests merged in 2023-02, with the labels that each got.

#162 Add tests for the HTTP tracker
  Cargo.lock
  Cargo.toml
  cSpell.json
  src/apis/middlewares/auth.rs
  src/apis/resources/peer.rs
  src/apis/responses.rs
  src/config.rs
  src/http/mod.rs
  src/http/response.rs
  src/jobs/http_tracker.rs
  src/protocol/info_hash.rs
  src/setup.rs
  src/tracker/auth.rs
  src/tracker/peer.rs
  src/tracker/services/torrent.rs
  tests/api/asserts.rs
  tests/api/client.rs
  tests/api/fixtures.rs
  tests/api/mod.rs
  tests/common/fixtures.rs
  tests/common/http.rs
  tests/common/mod.rs
  tests/http/asserts.rs
  tests/http/bencode.rs
  tests/http/client.rs
  tests/http/connection_info.rs
  tests/http/mod.rs
  tests/http/requests/announce.rs
  tests/http/requests/mod.rs
  tests/http/requests/scrape.rs
  tests/http/responses/announce.rs
  tests/http/responses/error.rs
  tests/http/responses/mod.rs
  tests/http/responses/scrape.rs
  tests/http/server.rs
  tests/http_tracker.rs
  tests/tracker_api.rs
Labels: add tests

#174 Isolate configuration and primitives in their own crates
  Cargo.lock
  Cargo.toml
  packages/configuration/Cargo.toml
  packages/configuration/src/lib.rs
  packages/primitives/Cargo.toml
  packages/primitives/src/lib.rs
  packages/test-helpers/Cargo.toml
  packages/test-helpers/src/config.rs
  packages/test-helpers/src/lib.rs
  src/apis/middlewares/auth.rs
  src/databases/driver.rs
  src/databases/mod.rs
  src/jobs/http_tracker.rs
  src/jobs/torrent_cleanup.rs
  src/jobs/tracker_apis.rs
  src/jobs/udp_tracker.rs
  src/lib.rs
  src/logging.rs
  src/main.rs
  src/setup.rs
  src/tracker/mod.rs
  src/tracker/services/common.rs
  src/tracker/services/statistics.rs
  src/tracker/services/torrent.rs
  src/udp/handlers.rs
  tests/api/server.rs
  tests/udp.rs
Labels: refactor, needs-rebase

#183 Remove duplicate code from `announce` request handlers
  src/http/warp_implementation/handlers.rs
  src/http/warp_implementation/mod.rs
  src/http/warp_implementation/peer_builder.rs
  src/tracker/mod.rs
  src/tracker/peer.rs
  src/tracker/torrent.rs
  src/udp/handlers.rs
  src/udp/mod.rs
  src/udp/peer_builder.rs
  src/udp/request.rs
Labels: refactor
