Repository torrust/torrust-tracker, pull requests merged in 2024-07, with the labels that each got.

#930 Update dependencies
  Cargo.lock
Labels: Dependencies

#931 ci: coverage workflow pre-build fix
  .github/workflows/coverage.yaml
Labels: Needs Rebase

#934 Config overhaul: split tracker mode
  Cargo.lock
  Cargo.toml
  packages/configuration/src/lib.rs
  packages/configuration/src/v1/core.rs
  packages/configuration/src/v1/mod.rs
  packages/primitives/src/lib.rs
  packages/test-helpers/Cargo.toml
  packages/test-helpers/src/configuration.rs
  src/app.rs
  src/bootstrap/jobs/http_tracker.rs
  src/bootstrap/jobs/tracker_apis.rs
  src/core/mod.rs
  src/lib.rs
  src/servers/apis/server.rs
  src/servers/http/server.rs
  src/servers/http/v1/handlers/announce.rs
  src/servers/http/v1/handlers/scrape.rs
  src/servers/http/v1/services/announce.rs
  src/servers/http/v1/services/scrape.rs
  src/servers/udp/handlers.rs
  src/servers/udp/server/mod.rs
  tests/servers/api/mod.rs
  tests/servers/http/v1/contract.rs
Labels: Code Cleanup / Refactoring

#940 Config overhaul: define current config version as version 2
  packages/configuration/src/lib.rs
  packages/configuration/src/v2/core.rs
  packages/configuration/src/v2/database.rs
  packages/configuration/src/v2/health_check_api.rs
  packages/configuration/src/v2/http_tracker.rs
  packages/configuration/src/v2/logging.rs
  packages/configuration/src/v2/mod.rs
  packages/configuration/src/v2/network.rs
  packages/configuration/src/v2/tracker_api.rs
  packages/configuration/src/v2/udp_tracker.rs
  src/bootstrap/jobs/torrent_cleanup.rs
Labels: Enhancement / Feature Request

#941 Config overhaul: improve admin experience
  Cargo.lock
  packages/configuration/Cargo.toml
  packages/configuration/src/lib.rs
  packages/configuration/src/v2/mod.rs
  src/app.rs
  src/bootstrap/app.rs
  src/bootstrap/logging.rs
  src/console/ci/e2e/logs_parser.rs
  src/console/ci/e2e/runner.rs
  src/console/clients/checker/app.rs
  src/console/clients/udp/app.rs
  src/console/profiling.rs
  src/main.rs
  src/servers/apis/mod.rs
Labels: Enhancement / Feature Request, UX

#942 Config overhaul: rename `log_level` to `threshold`
  docs/benchmarking.md
  packages/configuration/src/lib.rs
  packages/configuration/src/v2/logging.rs
  packages/configuration/src/v2/mod.rs
  packages/test-helpers/src/configuration.rs
  share/default/config/tracker.udp.benchmarking.toml
  src/bootstrap/app.rs
  src/bootstrap/logging.rs
  src/console/ci/e2e/logs_parser.rs
  src/core/mod.rs
  src/lib.rs
Labels: Enhancement / Feature Request, - Admin -, UX

#946 Update dependencies
  .github/workflows/container.yaml
  Cargo.lock
Labels: Dependencies

#947 Config overhaul: add version and namespace to the configuration
  packages/configuration/src/lib.rs
  packages/configuration/src/v2/mod.rs
  share/default/config/tracker.container.mysql.toml
  share/default/config/tracker.container.sqlite3.toml
  share/default/config/tracker.development.sqlite3.toml
  share/default/config/tracker.e2e.container.sqlite3.toml
  share/default/config/tracker.udp.benchmarking.toml
Labels: Enhancement / Feature Request

#975 New API endpoint to upload pre-existing keys
  src/core/auth.rs
  src/core/mod.rs
  src/servers/apis/v1/context/auth_key/forms.rs
  src/servers/apis/v1/context/auth_key/handlers.rs
  src/servers/apis/v1/context/auth_key/mod.rs
  src/servers/apis/v1/context/auth_key/responses.rs
  src/servers/apis/v1/context/auth_key/routes.rs
  src/servers/apis/v1/responses.rs
  tests/servers/api/v1/asserts.rs
  tests/servers/api/v1/client.rs
  tests/servers/api/v1/contract/context/auth_key.rs
Labels: Enhancement / Feature Request

#980 Do not allow invalid tracker keys
  src/core/auth.rs
  tests/servers/api/v1/asserts.rs
  tests/servers/api/v1/contract/context/auth_key.rs
Labels: Bug
