Repository torrust/torrust-tracker, pull requests merged in 2024-05, with the labels that each got.

#832 Update dependencies
  Cargo.lock
  Cargo.toml
Labels: Dependencies

#839 Bump `ringbuf` from `0.3.3` to `0.4.0`
  Cargo.lock
  Cargo.toml
  src/servers/udp/server.rs
Labels: Dependencies

#840 Update dependencies
  Cargo.lock
Labels: Dependencies

#841 feat: log aborted UDP requests
  src/servers/udp/server.rs
Labels: Enhancement / Feature Request

#844 chore(deps): bump `rustc-demangle` from `v0.1.23` to `v0.1.24`
  Cargo.lock
Labels: Dependencies

#847 docs: fix profiling docs
  docs/media/flamegraph_generated_without_sudo.svg
  docs/media/flamegraph_generated_withput_sudo.svg
  docs/profiling.md
Labels: Documentation, Code Cleanup / Refactoring

#808 Use `figment` for configuration
  Cargo.lock
  Cargo.toml
  packages/configuration/Cargo.toml
  packages/configuration/src/lib.rs
  packages/configuration/src/v1/health_check_api.rs
  packages/configuration/src/v1/http_tracker.rs
  packages/configuration/src/v1/mod.rs
  packages/configuration/src/v1/tracker_api.rs
  packages/configuration/src/v1/udp_tracker.rs
  share/default/config/tracker.container.mysql.toml
  share/default/config/tracker.container.sqlite3.toml
  share/default/config/tracker.development.sqlite3.toml
  share/default/config/tracker.e2e.container.sqlite3.toml
  share/default/config/tracker.udp.benchmarking.toml
Labels: Code Cleanup / Refactoring

#854 Refactor: enrich field types in configuration structs
  Cargo.lock
  Cargo.toml
  cSpell.json
  packages/configuration/Cargo.toml
  packages/configuration/src/lib.rs
  packages/configuration/src/v1/core.rs
  packages/configuration/src/v1/health_check_api.rs
  packages/configuration/src/v1/http_tracker.rs
  packages/configuration/src/v1/mod.rs
  packages/configuration/src/v1/tracker_api.rs
  packages/configuration/src/v1/udp_tracker.rs
  packages/test-helpers/src/configuration.rs
  src/app.rs
  src/bootstrap/jobs/health_check_api.rs
  src/bootstrap/jobs/http_tracker.rs
  src/bootstrap/jobs/mod.rs
  src/bootstrap/jobs/torrent_cleanup.rs
  src/bootstrap/jobs/tracker_apis.rs
  src/bootstrap/jobs/udp_tracker.rs
  src/bootstrap/logging.rs
  src/core/mod.rs
  src/core/services/mod.rs
  src/servers/apis/mod.rs
  src/servers/apis/server.rs
  src/servers/http/server.rs
  src/servers/http/v1/extractors/client_ip_sources.rs
  src/servers/http/v1/services/announce.rs
  src/servers/udp/handlers.rs
  src/servers/udp/server.rs
  tests/servers/api/environment.rs
  tests/servers/health_check_api/environment.rs
  tests/servers/http/environment.rs
  tests/servers/udp/environment.rs
Labels: Code Cleanup / Refactoring

#858 Use only non-defaults in `toml` config templates
  packages/configuration/src/lib.rs
  packages/configuration/src/v1/core.rs
  packages/configuration/src/v1/health_check_api.rs
  packages/configuration/src/v1/http_tracker.rs
  packages/configuration/src/v1/tracker_api.rs
  packages/configuration/src/v1/udp_tracker.rs
  share/default/config/tracker.container.mysql.toml
  share/default/config/tracker.container.sqlite3.toml
  share/default/config/tracker.development.sqlite3.toml
  share/default/config/tracker.e2e.container.sqlite3.toml
  share/default/config/tracker.udp.benchmarking.toml
Labels: Code Cleanup / Refactoring

#859 Update dependencies
  Cargo.lock
Labels: Dependencies

#860 Show `toml` file location in Figment errors
  packages/configuration/src/lib.rs
  packages/configuration/src/v1/mod.rs
  src/bootstrap/config.rs
Labels: Enhancement / Feature Request, Code Cleanup / Refactoring

#862 Update README
  README.md
Labels: Documentation, Enhancement / Feature Request

#863 Fix Roadmap in README
  README.md
Labels: Documentation

#865 Add timeouts for Axum server in the Tracker API
  Cargo.lock
  Cargo.toml
  cSpell.json
  src/servers/apis/routes.rs
  src/servers/apis/server.rs
  src/servers/custom_axum_server.rs
  src/servers/mod.rs
Labels: Security, - Admin -

#875 Fix and improved bootstrap jobs module test.
  src/bootstrap/jobs/mod.rs
Labels: Testing

#871 Add privacy methods to the `TrackerMode` enum
  packages/primitives/src/lib.rs
  src/core/mod.rs
Labels: Needs Rebase

#881 Update dependencies
  Cargo.lock
  cSpell.json
  packages/clock/src/lib.rs
  packages/test-helpers/src/configuration.rs
  src/bootstrap/jobs/http_tracker.rs
  src/bootstrap/jobs/tracker_apis.rs
  src/bootstrap/jobs/udp_tracker.rs
  src/console/clients/udp/checker.rs
  src/console/profiling.rs
  src/core/databases/mod.rs
  src/core/mod.rs
  src/core/torrent/mod.rs
  src/lib.rs
  src/servers/apis/mod.rs
  src/servers/apis/v1/context/auth_key/handlers.rs
  src/servers/apis/v1/context/auth_key/mod.rs
  src/servers/apis/v1/context/torrent/resources/torrent.rs
  src/servers/apis/v1/context/whitelist/handlers.rs
  src/servers/apis/v1/context/whitelist/mod.rs
  src/servers/apis/v1/mod.rs
  src/servers/http/mod.rs
  src/servers/http/server.rs
  src/servers/http/v1/extractors/authentication_key.rs
  src/servers/http/v1/requests/announce.rs
  src/servers/http/v1/responses/error.rs
  src/servers/http/v1/routes.rs
  src/servers/http/v1/services/announce.rs
  src/servers/http/v1/services/scrape.rs
  src/servers/udp/connection_cookie.rs
  src/servers/udp/handlers.rs
  src/servers/udp/mod.rs
  src/servers/udp/peer_builder.rs
  src/servers/udp/server.rs
Labels: Dependencies
