Repository torrust/torrust-tracker, pull requests merged in 2024-04, with the labels that each got.

#769 Udpate profiling docs
  .cargo/config.toml
  Cargo.toml
  cSpell.json
  docs/media/flamegraph.svg
  docs/media/flamegraph_generated_withput_sudo.svg
  docs/profiling.md
  flamegraph_generated_withput_sudo.svg
Labels: Documentation

#778 Performance optimization: create a new torrent repository using a `SkipMap` instead of a `BTreeMap`
  Cargo.lock
  Cargo.toml
  cSpell.json
  packages/torrent-repository/Cargo.toml
  packages/torrent-repository/benches/repository_benchmark.rs
  packages/torrent-repository/src/lib.rs
  packages/torrent-repository/src/repository/mod.rs
  packages/torrent-repository/src/repository/rw_lock_std.rs
  packages/torrent-repository/src/repository/rw_lock_tokio.rs
  packages/torrent-repository/src/repository/skip_map_mutex_std.rs
  packages/torrent-repository/tests/common/repo.rs
  packages/torrent-repository/tests/repository/mod.rs
  src/core/torrent/mod.rs
Labels: Optimization

#780 Update dependencies
  Cargo.lock
Labels: Dependencies

#784 Performance optimization: create a new torrent repository using `DashMap`
  Cargo.lock
  Cargo.toml
  cSpell.json
  packages/torrent-repository/Cargo.toml
  packages/torrent-repository/benches/repository_benchmark.rs
  packages/torrent-repository/src/lib.rs
  packages/torrent-repository/src/repository/dash_map_mutex_std.rs
  packages/torrent-repository/src/repository/mod.rs
  packages/torrent-repository/tests/common/repo.rs
  packages/torrent-repository/tests/repository/mod.rs
Labels: Optimization

#792 Refactor: segregate command and query for announce request
  packages/torrent-repository/benches/helpers/asyn.rs
  packages/torrent-repository/benches/helpers/sync.rs
  packages/torrent-repository/src/entry/mod.rs
  packages/torrent-repository/src/entry/mutex_std.rs
  packages/torrent-repository/src/entry/mutex_tokio.rs
  packages/torrent-repository/src/entry/single.rs
  packages/torrent-repository/src/repository/dash_map_mutex_std.rs
  packages/torrent-repository/src/repository/mod.rs
  packages/torrent-repository/src/repository/rw_lock_std.rs
  packages/torrent-repository/src/repository/rw_lock_std_mutex_std.rs
  packages/torrent-repository/src/repository/rw_lock_std_mutex_tokio.rs
  packages/torrent-repository/src/repository/rw_lock_tokio.rs
  packages/torrent-repository/src/repository/rw_lock_tokio_mutex_std.rs
  packages/torrent-repository/src/repository/rw_lock_tokio_mutex_tokio.rs
  packages/torrent-repository/src/repository/skip_map_mutex_std.rs
  packages/torrent-repository/tests/common/repo.rs
  packages/torrent-repository/tests/common/torrent.rs
  packages/torrent-repository/tests/entry/mod.rs
  packages/torrent-repository/tests/repository/mod.rs
  src/core/mod.rs
  src/core/services/torrent.rs
  src/servers/udp/handlers.rs
  tests/servers/api/environment.rs
  tests/servers/http/environment.rs
  tests/servers/udp/environment.rs
Labels: Code Cleanup / Refactoring, - Developer -

#793 Update dependencies
  Cargo.lock
Labels: Dependencies

#797 Refactor: extract peer list in torrent repository entry
  packages/primitives/src/peer.rs
  packages/torrent-repository/src/entry/mod.rs
  packages/torrent-repository/src/entry/peer_list.rs
  packages/torrent-repository/src/entry/single.rs
  packages/torrent-repository/src/repository/dash_map_mutex_std.rs
  packages/torrent-repository/src/repository/rw_lock_std.rs
  packages/torrent-repository/src/repository/rw_lock_std_mutex_std.rs
  packages/torrent-repository/src/repository/rw_lock_std_mutex_tokio.rs
  packages/torrent-repository/src/repository/rw_lock_tokio.rs
  packages/torrent-repository/src/repository/rw_lock_tokio_mutex_std.rs
  packages/torrent-repository/src/repository/rw_lock_tokio_mutex_tokio.rs
  packages/torrent-repository/src/repository/skip_map_mutex_std.rs
Labels: Code Cleanup / Refactoring

#800 Torrent repository with `parking_lot` crate locks
  Cargo.lock
  Cargo.toml
  packages/torrent-repository/Cargo.toml
  packages/torrent-repository/benches/repository_benchmark.rs
  packages/torrent-repository/src/entry/mod.rs
  packages/torrent-repository/src/entry/mutex_parking_lot.rs
  packages/torrent-repository/src/entry/rw_lock_parking_lot.rs
  packages/torrent-repository/src/lib.rs
  packages/torrent-repository/src/repository/skip_map_mutex_std.rs
  packages/torrent-repository/tests/common/repo.rs
  packages/torrent-repository/tests/common/torrent.rs
  packages/torrent-repository/tests/entry/mod.rs
  packages/torrent-repository/tests/repository/mod.rs
Labels: Optimization

#810 chore:[#674] Tracker Checker: Ouput in JSON
  Cargo.lock
  Cargo.toml
  src/console/clients/checker/checks/health.rs
  src/console/clients/checker/checks/http.rs
  src/console/clients/checker/checks/mod.rs
  src/console/clients/checker/checks/structs.rs
  src/console/clients/checker/checks/udp.rs
  src/console/clients/checker/service.rs
Labels: Enhancement / Feature Request
