Repository torrust/torrust-tracker, pull requests merged in 2024-03, with the labels that each got.

#726 Fix linting errors
  packages/configuration/src/lib.rs
  packages/primitives/src/lib.rs
  packages/test-helpers/src/configuration.rs
  src/servers/udp/error.rs
Labels: Code Cleanup / Refactoring

#728 Feat: add a new info_hash URL query array to the torrent list endpoint
  Cargo.lock
  Cargo.toml
  src/core/services/torrent.rs
  src/servers/apis/v1/context/torrent/handlers.rs
  tests/servers/api/v1/contract/context/torrent.rs
Labels: Enhancement / Feature Request

#732 Docs: benchmarking
  README.md
  cSpell.json
  docs/benchmarking.md
  share/default/config/tracker.udp.benchmarking.toml
  src/console/clients/udp/responses.rs
  tests/README.md
  tests/wrk_benchmark_announce.lua
Labels: Documentation

#740 dev: bugfix completed download stat
  src/core/torrent/mod.rs
Labels: Bug

#741 Fix error messages starting UDP tracker
  src/servers/udp/server.rs
Labels: Bug

#747 Profiling for the UDP tracker
  .gitignore
  cSpell.json
  share/default/config/tracker.udp.benchmarking.toml
  src/bin/profiling.rs
  src/console/mod.rs
  src/console/profiling.rs
  src/servers/udp/server.rs
Labels: Optimization

#749 Add configuration for cargo flamegprah and docs for profiling
  .gitignore
  Cargo.toml
  cSpell.json
  docs/media/kcachegrind-screenshot.png
  docs/profiling.md
Labels: Documentation, Optimization

#750 Minor fixes
  .gitignore
  docs/media/flamegraph.svg
  src/servers/udp/server.rs
Labels: Bug
