Repository torrust/torrust-tracker, pull requests merged in 2024-10, with the labels that each got.

#1058 Fix vairous issues in the ci.
  .github/workflows/deployment.yaml
  .github/workflows/testing.yaml
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
Labels: Bug, Continuous Integration

#1062 docs: update release process
  docs/release_process.md
Labels: Documentation, Installer | Package

#1064 #1040: `continue` when finding errors
  src/console/clients/checker/checks/udp.rs
Labels: Bug
