Repository torrust/torrust-tracker, pull requests merged in 2024-06, with the labels that each got.

#887 Update dependencies
  Cargo.lock
Labels: Dependencies

#888 Move from `log` to `tracing` crate
  Cargo.lock
  Cargo.toml
  packages/configuration/src/lib.rs
  packages/located-error/Cargo.toml
  packages/located-error/src/lib.rs
  share/default/config/tracker.e2e.container.sqlite3.toml
  src/app.rs
  src/bootstrap/jobs/health_check_api.rs
  src/bootstrap/jobs/http_tracker.rs
  src/bootstrap/jobs/mod.rs
  src/bootstrap/jobs/torrent_cleanup.rs
  src/bootstrap/jobs/tracker_apis.rs
  src/bootstrap/jobs/udp_tracker.rs
  src/bootstrap/logging.rs
  src/console/ci/e2e/docker.rs
  src/console/ci/e2e/logs_parser.rs
  src/console/ci/e2e/runner.rs
  src/console/ci/e2e/tracker_checker.rs
  src/console/ci/e2e/tracker_container.rs
  src/console/clients/checker/app.rs
  src/console/clients/checker/checks/http.rs
  src/console/clients/checker/checks/udp.rs
  src/console/clients/udp/app.rs
  src/console/clients/udp/checker.rs
  src/console/profiling.rs
  src/core/auth.rs
  src/core/databases/mysql.rs
  src/core/mod.rs
  src/core/statistics.rs
  src/main.rs
  src/servers/apis/server.rs
  src/servers/apis/v1/context/torrent/handlers.rs
  src/servers/health_check_api/server.rs
  src/servers/http/server.rs
  src/servers/http/v1/handlers/announce.rs
  src/servers/http/v1/handlers/scrape.rs
  src/servers/registar.rs
  src/servers/signals.rs
  src/servers/udp/handlers.rs
  src/servers/udp/server.rs
  src/shared/bit_torrent/tracker/udp/client.rs
  tests/servers/health_check_api/environment.rs
Labels: Code Cleanup / Refactoring, Dependencies

#894 Update benchmarking docs
  docs/benchmarking.md
  docs/media/torrent-repository-implementations-benchmarking-report.png
Labels: Documentation

#895 Update dependencies
  Cargo.lock
Labels: Dependencies

#896 Enable colour in console output
  Cargo.lock
  Cargo.toml
  src/bootstrap/logging.rs
  src/console/ci/e2e/logs_parser.rs
  src/console/ci/e2e/runner.rs
  src/console/clients/checker/app.rs
  src/console/clients/udp/app.rs
Labels: Enhancement / Feature Request

#899 Fixes docker build error: `failed to load bitcode of module criterion ...`
  Cargo.toml
Labels: Bug

#897 Configuration overhaul: version 2 for the configuration toml file (breaking changes)
  Cargo.toml
  Containerfile
  compose.yaml
  docs/benchmarking.md
  docs/containers.md
  packages/configuration/Cargo.toml
  packages/configuration/src/lib.rs
  packages/configuration/src/v1/core.rs
  packages/configuration/src/v1/database.rs
  packages/configuration/src/v1/http_tracker.rs
  packages/configuration/src/v1/logging.rs
  packages/configuration/src/v1/mod.rs
  packages/configuration/src/v1/network.rs
  packages/configuration/src/v1/tracker_api.rs
  packages/configuration/src/v1/udp_tracker.rs
  packages/test-helpers/src/configuration.rs
  packages/torrent-repository/tests/entry/mod.rs
  packages/torrent-repository/tests/repository/mod.rs
  share/container/entry_script_sh
  share/default/config/tracker.container.mysql.toml
  share/default/config/tracker.container.sqlite3.toml
  share/default/config/tracker.development.sqlite3.toml
  share/default/config/tracker.e2e.container.sqlite3.toml
  share/default/config/tracker.udp.benchmarking.toml
  src/app.rs
  src/bootstrap/jobs/http_tracker.rs
  src/bootstrap/jobs/mod.rs
  src/bootstrap/jobs/tracker_apis.rs
  src/bootstrap/logging.rs
  src/console/ci/e2e/logs_parser.rs
  src/core/mod.rs
  src/lib.rs
  src/servers/apis/mod.rs
  src/servers/apis/server.rs
  src/servers/http/server.rs
  src/servers/http/v1/services/announce.rs
  src/servers/udp/handlers.rs
  src/servers/udp/server.rs
  tests/servers/api/environment.rs
  tests/servers/http/environment.rs
  tests/servers/udp/environment.rs
Labels: Enhancement / Feature Request

#906 Update dependencies
  Cargo.lock
Labels: Dependencies

#873 Implment Request Stream for UDP Tracker
  .cargo/config.toml
  cSpell.json
  src/lib.rs
  src/servers/udp/handlers.rs
  src/servers/udp/server.rs
  src/shared/bit_torrent/tracker/udp/client.rs
  tests/servers/udp/contract.rs
  tests/servers/udp/environment.rs
Labels: Code Cleanup / Refactoring

#913 Minor UDP server refactorings
  src/bootstrap/jobs/health_check_api.rs
  src/bootstrap/jobs/udp_tracker.rs
  src/console/ci/e2e/logs_parser.rs
  src/lib.rs
  src/servers/apis/mod.rs
  src/servers/apis/routes.rs
  src/servers/apis/server.rs
  src/servers/health_check_api/mod.rs
  src/servers/health_check_api/server.rs
  src/servers/http/mod.rs
  src/servers/http/server.rs
  src/servers/http/v1/routes.rs
  src/servers/logging.rs
  src/servers/mod.rs
  src/servers/udp/handlers.rs
  src/servers/udp/logging.rs
  src/servers/udp/mod.rs
  src/servers/udp/server.rs
  src/servers/udp/server/bound_socket.rs
  src/servers/udp/server/launcher.rs
  src/servers/udp/server/mod.rs
  src/servers/udp/server/receiver.rs
  src/servers/udp/server/request_buffer.rs
  src/servers/udp/server/spawner.rs
  src/servers/udp/server/states.rs
  src/shared/bit_torrent/tracker/udp/client.rs
  tests/servers/health_check_api/environment.rs
  tests/servers/udp/environment.rs
  tests/servers/udp/mod.rs
Labels: Code Cleanup / Refactoring

#919 Fix: clients output in JSON should not include logging
  src/console/clients/checker/app.rs
  src/console/clients/udp/app.rs
Labels: Bug
